# Docker
# Build a Docker image
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- development

resources:
- repo: self

variables:
  tag: '$(Build.BuildId)'
  isDockerNeeded : '$'

stages:
- stage: Build
  displayName: Build image
  jobs:
  - job: Build
    displayName: Build
    pool:
      vmImage: windows-latest
    steps:
    - task: Docker@2
      displayName: Build an image
      enabled: false
      inputs:
        command: build
        dockerfile: '$(Build.SourcesDirectory)/Dockerfile'
        tags: |
          $(tag)
    - task: DotNetCoreCLI@2
      displayName: Build selenium tests
      inputs:
       command: 'build'
       projects: 'Tests/SeleniumTests/SeleniumTests/SeleniumTests.csproj'
    - task: PublishBuildArtifacts@1
      inputs:
        PathtoPublish: 'Tests/SeleniumTests/SeleniumTests/'
        ArtifactName: 'continious_integration'
        publishLocation: 'Container'

- stage: 
  displayName: Run Selenium Tests
  jobs: 
    - job: Tests
      displayName: Run Test
      steps:
      - task: VSTest@3
        displayName: Run Selenium tests
        inputs:
          testSelector: 'testAssemblies'
          testAssemblyVer2: 'Tests/SeleniumTests/SeleniumTests/bin/Debug/net6.0/SeleniumTests.dll'
          searchFolder: '$(System.DefaultWorkingDirectory)'