# Docker
# Build a Docker image
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- development

resources:
- repo: self

variables:
  tag: '$(Build.BuildId)'
  isDockerNeeded : '$'

stages:
- stage: Build
  displayName: Build image
  jobs:
  - job: BuildJob
    displayName: Build
    pool:
      vmImage: ubuntu-latest
    steps:
    - task: Docker@2
      displayName: Build and push image
      inputs:
        command: 'buildAndPush'
        Dockerfile: '**/Dockerfile'

  - job: Tests
    displayName: Run Selenium tests
    dependsOn: BuildJob
    pool:
      vmImage: windows-latest
    steps:
     - task: DotNetCoreCLI@2
       displayName: Build selenium tests
       inputs:
        command: 'build'
        projects: 'Tests/SeleniumTests/SeleniumTests/SeleniumTests.csproj'
     - task: VSTest@3
       displayName: Run tests
       inputs:
          testSelector: 'testAssemblies'
          testAssemblyVer2: 'Tests/SeleniumTests/SeleniumTests/bin/Debug/net6.0/SeleniumTests.dll'
          searchFolder: '$(System.DefaultWorkingDirectory)'
     - task: PublishBuildArtifacts@1
       inputs:
         PathtoPublish: 'Tests/SeleniumTests/SeleniumTests/'
         ArtifactName: 'continious_integration'
         publishLocation: 'Container'